defaults:
  - envgen: cma_mae
  - eval: libero_spatial
  - _self_

hydra:
  run:
    dir: ./outputs/${hydra:runtime.choices.envgen}/${now:%Y-%m-%d_%H%M%S}

# for embedding collection
num_embeddings_each_task: 32
collect_embeddings_sigma: 0.04
save_embeddings_to: ${hydra:runtime.output_dir}/embeddings

# search_itr * emitter_batch_size * trials_per_sol
env_search_num_evals: ${oc.mul:100, ${envgen.emitter.batch_size}, ${eval.task_eval.num_trials_per_sol}}
log_every: ${oc.mul:5, ${envgen.emitter.batch_size}, ${eval.task_eval.num_trials_per_sol}} # Log every 5 search iterations
seed: 42

single_process: ${oc.equals:${oc.len:${oc.env_csv:VLA_SERVER_URIs}}, 1} # If True, there will be no dask parallelization and all evals will be done sequentially

# for resuming an experiment
reload_from_dir: null

# for exporting training and test datasets
proportion_of_vanilla_data_to_mix: 1.0
test_env_holdout_prob: 0.2
output_dataset_id: ${hydra:runtime.choices.envgen}