defaults:
  - measure_model: pca_measure
  - _self_

task_ids: [0]

task_eval:
  _target_: src.eval.JacoEval
  objective_func: adversarial
  measure_func: policy_embedding
  num_trials_per_sol: ${oc.len:${.vla_server_uris}}
  max_steps: 220
  num_steps_wait: 10
  replan_steps: 5
  vla_server_uris: ${oc.env_csv:VLA_SERVER_URIs}
  seed: ${seed}
  repair_config:
    time_limit: 1500
    seed: ${seed}
  camera_heights: 224
  camera_widths: 224